#!/usr/bin/python

# This file is used as a global config file while PCBmodE is running.
# DO NOT EDIT THIS FILE

cfg = {} # PCBmodE config
brd = {} # board
rte = {} # routing
stl = {} # style
pth = {} # cache
msg = {} # messages
stk = {} # stackup
tmp = {} # temp

