#!/usr/bin/python

# This file is used as a global config file while PCBmodE is running.
# DO NOT EDIT THIS FILE

cfg = {} # PCBmodE configuration
brd = {} # board data
stl = {} # style data
pth = {} # path database
msg = {} # message database
stk = {} # stackup data

